### ISSUE TITLE
Entrega 2 e 3

### ISSUE THREAD

**Issue by lucascunhaiftm** [GustavoBispo11/Gustavo_Bispo#2]
Deve ser feito o merge das branches com a master.
As customizações do rodapé não está formato alinhado.
A posição das imagens da imagens dos jogos deverão ser centralizadas, observe a propriedade margin: auto.
Estilo do menu lateral está fora do padrão.
Assim como programação desktop, a estética do arquivo fonte facilita a manutenção e legibilidade.

**Comment by GustavoBispo11** [comment]
ok

Em seg., 25 de mai. de 2020 às 14:53, Lucas Cunha <notifications@github.com>
escreveu:
